name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint:check

      - name: Check formatting
        run: npm run format:check

      - name: Run tests
        run: npm test

      - name: Run coverage
        run: npm run coverage

      - name: Upload coverage to Codecov
        if: matrix.node-version == '20.x'
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          fail_ci_if_error: false

      - name: Update coverage badge
        if: matrix.node-version == '20.x' && github.ref == 'refs/heads/main'
        run: |
          # Extract coverage percentage from lcov.info
          COVERAGE=$(grep -o 'LF:\|LH:' coverage/lcov.info | grep -c 'LH:' || echo 0)
          TOTAL=$(grep -o 'LF:\|LH:' coverage/lcov.info | grep -c 'LF:' || echo 1)
          PERCENTAGE=$(echo "scale=1; $COVERAGE * 100 / $TOTAL" | bc -l || echo "0")

          # Determine badge color
          if (( $(echo "$PERCENTAGE >= 90" | bc -l) )); then
            COLOR="brightgreen"
          elif (( $(echo "$PERCENTAGE >= 80" | bc -l) )); then
            COLOR="green"
          elif (( $(echo "$PERCENTAGE >= 70" | bc -l) )); then
            COLOR="yellow"
          elif (( $(echo "$PERCENTAGE >= 60" | bc -l) )); then
            COLOR="orange"
          else
            COLOR="red"
          fi

          # Update README badge
          sed -i "s|\[coverage-badge\]: https://img.shields.io/badge/test%20coverage-[^-]*-[^]]*|\[coverage-badge\]: https://img.shields.io/badge/test%20coverage-${PERCENTAGE}%25-${COLOR}|g" README.md

          # Check if there are changes to commit
          if ! git diff --quiet README.md; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add README.md
            git commit -m "chore: update coverage badge to ${PERCENTAGE}%"
            git push
          fi

  integration:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run MCP integration tests
        run: npm run test:mcp
